### ISSUE TITLE
Reduce verbosity of stack-traces in failing mutations

### ISSUE THREAD

**Issue by kevinjalbert** [david-schuler/javalanche#10]
When I run Javalanche I end up seeing a lot of unnecessary stack-traces of errors that occur due to the mutations. I have been unable to quite this down (I have manually changed log4j.properties as well as adjusted the _javalanche.log.level_).

```
 [exec] runMutationsCoverage:
 [exec] 
 [exec] javalancheTask:
 [exec]     [junit] Run mutation tests with tracing of coverage data per test
 [exec]     [junit] Applying 1th mutation with id 1. Running 280 tests
 [exec]     [junit] Applying 2th mutation with id 2. Running 280 tests
 [exec]     [junit] Applying 3th mutation with id 3. Running 111 tests
 [exec]     [junit] org.jgap.InvalidConfigurationException: The FitnessFunction instance must not be null.
 [exec]     [junit]     at org.jgap.Configuration.setFitnessFunction(Unknown Source)
 [exec]     [junit]     at org.jgap.MyThread.run(Unknown Source)
 [exec]     [junit]     at java.lang.Thread.run(Thread.java:679)
 [exec]     [junit] org.jgap.InvalidConfigurationException: The FitnessFunction instance must not be null.
 [exec]     [junit]     at org.jgap.Configuration.setFitnessFunction(Unknown Source)
 [exec]     [junit]     at org.jgap.MyThread.run(Unknown Source)
 [exec]     [junit]     at java.lang.Thread.run(Thread.java:679)
 [exec]     [junit] Applying 4th mutation with id 4. Running 110 tests
 [exec]     [junit] org.jgap.InvalidConfigurationException: The bulk fitness function and normal fitness function may not both be set.
 [exec]     [junit]     at org.jgap.Configuration.setFitnessFunction(Unknown Source)
 [exec]     [junit]     at org.jgap.MyThread.run(Unknown Source)
 [exec]     [junit]     at java.lang.Thread.run(Thread.java:679)
 ...
```

I was wondering if there is a way to remove these stack-traces from the output using a parameter (as some might not be interested in this information).

**Comment by david-schuler** [comment]
This is currently not supported by Javalanche. Technically it would be possible by directing System.err somewhere else. However, this would also swallow exceptions thrown by Javalanche. Therefore, it is not implemented yet.
I think that redirecting _stderr_ might work (as described [here](http://stackoverflow.com/questions/2342826/how-to-pipe-stderr-and-not-stdout)).

**Comment by kevinjalbert** [comment]
I'm closing this issue as a great deal of time has passed. If there is renewed interest just reopen or make a new issue and link to this one.
