### ISSUE TITLE
Coverage Impact for Javalanche-0.4 (Equivalent Mutants)

### ISSUE THREAD

**Issue by kevinjalbert** [david-schuler/javalanche#4]
I am using Javalanche on an open source project and I am trying to take into account _Equivalent Mutants_. I found out that Javalanche does not handle equivalent mutants automatically (which I kind of expected), but instead requires the addition of [Coverage Impact Analysis](https://github.com/david-schuler/javalanche/blob/master/src/main/resources/coverage-include.xml). I decided to try using it and followed the provided [Example Triangle Coverage Impact](https://github.com/david-schuler/javalanche/wiki/Example-Triangle-Coverage-Impact) for Javalanche-0.4 (as of 2fa6e1a48ad84777d352554a1587c2e08dc16557) and it does not function correctly.

It seem as if the _createCoverageData_ and _runMutationsCoverage_ tasks do nothing (the following shows the output of this task for the provided example using a _log.level=DEBUG_) and in the ending no mutants were evaluated:

```
> ant -f javalanche.xml -Dprefix=triangle -Dcp=target/classes/:./lib/junit.jar -Dtests=triangle.tests.TriangleTestSuite -Djavalanche=../../ -Djavalanche.log.level=DEBUG createCoverageData
Buildfile: /home/jalbert/workspace/javalanche/javalanche-0.4/examples/triangle/javalanche.xml

mutationDir:

createCoverageData:

javalancheTask:
    [junit] Tests run: 18
    [junit] Failing Tests: 0

BUILD SUCCESSFUL
Total time: 1 second
```

After looking around I quickly found the following comment in the [javalanche.xml](https://github.com/david-schuler/javalanche/blob/master/javalanche.xml#L26) mentioning that the ability _"to compute the coverage or invariant impact (not supported in current version) of the mutations"_.

I created this issue to raise this lack of functionality in the latest version. I hope that eventually this will be added back in.

**Comment by david-schuler** [comment]
Theoretically, the functionality for the coverage impact is there. However, this comment in the _javalanche.xml_ file is a bit misleading and the example in the Wiki is missing a step.  I changed the comment in  _javalanche.xml_ (dc4de474bfff087f482356251d94db8ee1c7d55c) and fixed the example in the wiki. I hope this solves your issue.

**Comment by kevinjalbert** [comment]
Still the _createCoverageData_ and _runMutationsCoverage_ tasks seem to do nothing. When I get to the final task (_analyzeResults_), It shows the results yet there is 0 mutants killed, which again shows that the two previous tasks are not  actually running/killing the mutants.

I want to say something probably happened between the conversion of Javalanche-0.3.6 to the current. Again I could be doing something wrong on my end, but if you could try the steps I did to see if you could reproduce the problem that would be great.
1. cloned dc4de47
2. `sh makeDist.sh`
3. `cd javalanche-0.4/examples/triangle/`
4. Followed every step of the example in the [Example Triangle Coverage Impact](https://github.com/david-schuler/javalanche/wiki/Example-Triangle-Coverage-Impact)

---

I did a little digging around and I found that the _createCoverageData_ task in the [coverage-include.xml](https://github.com/david-schuler/javalanche/blob/master/src/main/resources/coverage-include.xml#L6) specifies that Javalanche should use the _create-coverage_ run-mode. I then found that this run-mode did not exist in the [RunMode.java](https://github.com/david-schuler/javalanche/blob/master/src/main/java/de/unisb/cs/st/javalanche/mutation/properties/RunMode.java) (and instead is _create-coverage-mult_). After using _blame_ I found that it was removed in the following [commit-diff](https://github.com/david-schuler/javalanche/commit/161966977bb8a8e181443012d31d93271393d6f4#L78L26). I don't know if this might be a cause for this problem it is just something I found (it might be intentionally for all I know).

**Comment by david-schuler** [comment]
Hi Kevin,

you were right. There were some things broken, because of the refactoring. I fixed them in this commit and updated the wiki page [Example Triangle Coverage Impact](https://github.com/david-schuler/javalanche/wiki/Example-Triangle-Coverage-Impact). 
Thank you for bringing this up and sorry for the inconvenience.

David

**Comment by kevinjalbert** [comment]
Great work! I am able to follow the example and get the expected results.

---

I was just curious about using the coverage impact though to filter out equivalent mutants. 

Javalanche uses the coverage impact of mutants to detect equivalent mutants. The results are displayed on the command-line interface by indicating the percentage of mutants over/under a determined epsilon. Within the HTML report there is a column dedicated to _Methods with Coverage Difference_ which contain an integer value. There is also a detailed analyze.csv of details for each mutant.

I am not 100% sure on how on to interpret the results to filter out equivalent mutants. If I combined the _de.unisb.cs.st.javalanche.coverage.CoverageAnalyzer_ with another analyzer would the equivalent mutants be removed? Or must I manually exclude those in my own analyzer, if so how can I determine which are equivalent easily from the provided data? For example, I do not see an obvious field pertaining to _is_equivalent_.

I figure I will have to manually filter these equivalent mutants out. I am just looking for a starting location to work from.

Again thanks a lot David, I am very pleased with how quick and effective you are at responding to issues.

**Comment by david-schuler** [comment]
The relation between coverage impact and equivalence is only a heuristic, i.e. the more coverage changes are caused by a mutation the more likely it is to be non-equivalent. Therefore, the output only contains the coverage impact. 
For our experiments we used the csv-files and filtered/sorted mutants from this data.
In order to reduce the number of equivalent mutants, one can focus on those mutations with the biggest impact, or only on mutations where the impact is bigger than a threshold. 
I hope this answers your question.
